blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [

	# Blogpage
	path('', views.blog_view, name='blog'),

	# Post Details
	path('post/<pid>/', views.blog_detail_view, name='blog-detail'),

	# Blog Category
	path('category/<cid>/', views.blog_category_view, name="blog-category"),

	# Blog Tags
	path('tag/<slug:tag_slug>/', views.blog_tags, name='blog-tag'),

	# Add Post Comment
	path('ajax-add-comment/<int:pid>/', views.ajax_add_comment, name='ajax-add-comment'),

]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [

	# Homepage
	path('', views.index, name='index'),
	
	# Product
	path('products/', views.products_list_view, name='products-list'),
	path('product/<pid>/', views.product_detail_view, name='products-detail'),

	# Category
	path('category/', views.category_list_view, name='category-list'),
	path('category/<cid>/', views.category_product_list_view, name='category-product-list'),

	# Vendor
	path('vendors/', views.vendor_list_view, name='vendor-list'),
	path('vendor/<vid>/', views.vendor_detail_view, name='vendor-detail'),

	# Tags
	path('products/tag/<slug:tag_slug>/', views.tags_list, name='tags'),

	# Add Product Review
	path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax-add-review'),

	# Seacrh 
	path('search/', views.search_view, name='search'),

	# Product Filter
	path('filter-product/', views.filter_product, name='filter-product'),

	# Add To Cart 
	path('add-to-cart/', views.add_to_cart, name='add-to-cart'),

	# Cart Page
	path('cart/', views.cart_view, name='cart'),

	# Delete from cart
	path('delete-from-cart/', views.delete_from_cart, name='delete-from-cart'),

	# Update cart
	path('update-cart/', views.update_cart, name='update-cart'),

	# Wishlist page
	path('wishlist/', views.wishlist_view, name='wishlist'),

	# Add To Wishlist
	path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),

	# Remove From Wishlist
	path('remove-from-wishlist/', views.remove_from_wishlist, name='remove-from-wishlist'),

	# Contact
	path('contact/', views.contact, name='contact'),

	# Ajax Contact From
	path('ajax-contact-form/', views.ajax_contact_form, name='ajax-contact-form'),

	# About Us
	path('about/', views.about, name='about'),
    
	# Checkout Page newly added
	path('checkout/', views.checkout, name='checkout'),
    
	# Order History
    path('order-history/', views.order_history, name='order-history'),
    path('order-detail/<str:order_id>/', views.order_detail, name='order-detail'),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


### TEST ###

# handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'

templates/partials/blog-sidebar.html
<div class="col-lg-4 col-md-5">
    <div class="blog__sidebar">
        <div class="blog__sidebar__search">
            <form action="#">
                <input type="text" placeholder="Search...">
                <button type="submit"><span class="icon_search"></span></button>
            </form>
        </div>
        <div class="blog__sidebar__item">
            <h4>Categories</h4>
            {% for c in blog_categories %}
            <ul>
                <li><a href="{% url 'blog:blog-category' c.cid %}">{{ c.title }} ({{c.categories.count}})</a></li>
            </ul>
            {% endfor %}
        </div>
        <!-- <div class="blog__sidebar__item">
            <h4>Recent News</h4>
            <div class="blog__sidebar__recent">
                <a href="#" class="blog__sidebar__recent__item">
                    <div class="blog__sidebar__recent__item__pic">
                        <img src="img/blog/sidebar/sr-1.jpg" alt="">
                    </div>
                    <div class="blog__sidebar__recent__item__text">
                        <h6>09 Kinds Of Vegetables<br /> Protect The Liver</h6>
                        <span>MAR 05, 2019</span>
                    </div>
                </a>
                <a href="#" class="blog__sidebar__recent__item">
                    <div class="blog__sidebar__recent__item__pic">
                        <img src="img/blog/sidebar/sr-2.jpg" alt="">
                    </div>
                    <div class="blog__sidebar__recent__item__text">
                        <h6>Tips You To Balance<br /> Nutrition Meal Day</h6>
                        <span>MAR 05, 2019</span>
                    </div>
                </a>
                <a href="#" class="blog__sidebar__recent__item">
                    <div class="blog__sidebar__recent__item__pic">
                        <img src="img/blog/sidebar/sr-3.jpg" alt="">
                    </div>
                    <div class="blog__sidebar__recent__item__text">
                        <h6>4 Principles Help You Lose <br />Weight With Vegetables</h6>
                        <span>MAR 05, 2019</span>
                    </div>
                </a>
            </div>
        </div> -->
        <div class="blog__sidebar__item">
            <h4>By Tags</h4>
            <div class="blog__sidebar__item__tags">
                {% for random_tag in random_blog_tags %}
                <a href="{% url 'blog:blog-tag' random_tag.slug %}">#{{ random_tag.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/partials/hero-section.html
<!-- Hero Section Begin -->
<section class="hero hero-normal">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All Categories</span>
                    </div>
                    <ul>
                        {% for c in categories %}
                        <li><a href="{% url 'core:category-product-list' c.cid %}">
                        {{ c.title }}
						</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form action="{% url 'core:search' %}" method="GET">
                            <!-- <div class="hero__search__categories">
                                All Categories
                                <span class="arrow_carrot-down"></span>
                            </div> -->
                            <input type="text" placeholder="What do yo u need?" name="q">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+12 34.567.888</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->