blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [

	# Blogpage
	path('', views.blog_view, name='blog'),

	# Post Details
	path('post/<pid>/', views.blog_detail_view, name='blog-detail'),

	# Blog Category
	path('category/<cid>/', views.blog_category_view, name="blog-category"),

	# Blog Tags
	path('tag/<slug:tag_slug>/', views.blog_tags, name='blog-tag'),

	# Add Post Comment
	path('ajax-add-comment/<int:pid>/', views.ajax_add_comment, name='ajax-add-comment'),

]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [

	# Homepage
	path('', views.index, name='index'),
	
	# Product
	path('products/', views.products_list_view, name='products-list'),
	path('product/<pid>/', views.product_detail_view, name='products-detail'),

	# Category
	path('category/', views.category_list_view, name='category-list'),
	path('category/<cid>/', views.category_product_list_view, name='category-product-list'),

	# Vendor
	path('vendors/', views.vendor_list_view, name='vendor-list'),
	path('vendor/<vid>/', views.vendor_detail_view, name='vendor-detail'),

	# Tags
	path('products/tag/<slug:tag_slug>/', views.tags_list, name='tags'),

	# Add Product Review
	path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax-add-review'),

	# Seacrh 
	path('search/', views.search_view, name='search'),

	# Product Filter
	path('filter-product/', views.filter_product, name='filter-product'),

	# Add To Cart 
	path('add-to-cart/', views.add_to_cart, name='add-to-cart'),

	# Cart Page
	path('cart/', views.cart_view, name='cart'),

	# Delete from cart
	path('delete-from-cart/', views.delete_from_cart, name='delete-from-cart'),

	# Update cart
	path('update-cart/', views.update_cart, name='update-cart'),

	# Wishlist page
	path('wishlist/', views.wishlist_view, name='wishlist'),

	# Add To Wishlist
	path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),

	# Remove From Wishlist
	path('remove-from-wishlist/', views.remove_from_wishlist, name='remove-from-wishlist'),

	# Contact
	path('contact/', views.contact, name='contact'),

	# Ajax Contact From
	path('ajax-contact-form/', views.ajax_contact_form, name='ajax-contact-form'),

	# About Us
	path('about/', views.about, name='about'),
    
	# Checkout Page newly added
	path('checkout/', views.checkout, name='checkout'),
    
	# Order History
    path('order-history/', views.order_history, name='order-history'),
    path('order-detail/<str:order_id>/', views.order_detail, name='order-detail'),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


### TEST ###

# handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [

	# User Auths
	path("sing-up/", views.register_view, name="sing-up"),
	path("sing-in/", views.login_view, name="sing-in"),
	path("sing-out/", views.logout_view, name="sing-out"),

	# User Account
	path("account/", views.account, name="account"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.html import mark_safe

class User(AbstractUser):
	email = models.EmailField(unique=True)
	username = models.CharField(max_length=100)
	name = models.CharField(max_length=100, null=True, blank=True, default='')
	phone = models.CharField(max_length=100, null=True, blank=True, default='')
	bio = models.CharField(max_length=100, null=True, blank=True, default='')
	image = models.ImageField(upload_to='account-images', default="user.jpg")

	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ['username']

	def user_image(self):
		return mark_safe('<img src="%s" width="50" height="50">' % (self.image.url))

	def __str__(self):
		return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
from django.core.exceptions import ValidationError

class UserRegisterForm(UserCreationForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'username-validation'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

	class Meta:
		model = User
		fields = ['username', 'email']

	def clean_username(self):
		username = self.cleaned_data['username']

		if ' ' in username:
			raise ValidationError("Username cannot contain spaces.")

		if len(username) < 3 or len(username) > 12:
			raise ValidationError("Username must be between 3 and 12 characters.")
			
		return username

userauths/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from userauths.models import User
from userauths.forms import UserRegisterForm

# User = settings.AUTH_USER_MODEL

def register_view(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST or None)

		if form.is_valid():
			new_user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f"Hey {username}, Your account was created successfully")
			new_user = authenticate(username=form.cleaned_data['email'], 
									password=form.cleaned_data['password1'] 	
				)
			login(request, new_user)

			return redirect("core:index")
	else:
		form = UserRegisterForm()

	context = {
		'form': form
	}

	return render(request, 'userauths/sing-up.html', context)

def login_view(request):
    if request.user.is_authenticated:
        return redirect('core:index')

    next_url = request.GET.get('next', None)

    if request.method == 'POST':
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in.")

                if next_url:
                    return redirect(next_url)
                else:
                    return redirect('core:index')
            else:
                messages.warning(request, "Password is wrong.")
        except User.DoesNotExist:
            messages.warning(request, f"User with {email} does not exist!")

    return render(request, 'userauths/sing-in.html')

def logout_view(request):
	logout(request)
	messages.success(request, "You logged out.")
	return redirect('userauths:sing-in')

@login_required
def account(request):
	if request.method == 'POST':
		
		new_username = request.POST.get('username').replace(" ", "").lower()

		if ' ' in new_username:
			messages.warning(request, "Username cannot contain spaces.")
			return redirect('userauths:account')

		if len(new_username) < 3 or len(new_username) > 12:
			messages.warning(request, 'Username must be between 3 and 12 characters.')
			return redirect('userauths:account')

		if User.objects.filter(username=new_username).exclude(id=request.user.id).exists():
			messages.warning(request, f'Username "{new_username}" is already taken!')
			return redirect('userauths:account')

		request.user.username = new_username
		request.user.save()

		new_name = request.POST.get('name')
		new_phone = request.POST.get('phone')
		new_bio = request.POST.get('bio')
		new_image = request.FILES.get('image')

		account = request.user
		account.name = new_name
		account.phone = new_phone
		account.bio = new_bio

		if new_image:
			account.image = new_image
			
		account.save()

		messages.success(request, 'Account updated successfully.')
		return redirect('userauths:account')
	return render(request, 'userauths/account.html')

		

templates/userauths/account.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Account{% endblock title %}

{% block content %}

<!-- Hero Section Begin -->
<section class="hero hero-normal">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All Categories</span>
                    </div>
                    <ul> 
                        {% for c in categories %}
                        <li><a href="{% url 'core:category-product-list' c.cid %}">
                        {{ c.title }}
                    	</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form action="{% url 'core:search' %}" method="GET">
                            <!-- <div class="hero__search__categories">
                                All Categories
                                <span class="arrow_carrot-down"></span>
                            </div> -->
                            <input type="text" placeholder="What do yo u need?" name="q">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+65 11.188.888</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'assets/img/breadcrumb.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Account</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'core:index' %}">Home</a>
                        <span class="breadcrumb__separator"><i class="fa fa-angle-right"></i></span>
                        <span>Account</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Account Section Start -->
<section class="my-5">
	<div class="container">
		<!-- <h1 class="mb-5">Account Settings</h1> -->
		<div class="custom-grey-bg shadow rounded-lg d-block d-sm-flex">
			<div class="profile-tab-nav border-right">
				<div class="p-4">
					<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="img-circle text-center mb-3">
						<img src="{{ user.image.url }}" alt="User" class="shadow">
						<!-- <input type="file" name="image"> -->
					</div>
					</form>
					<h4 class="text-center">{{ user.name }}</h4>
				</div>
				<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
					<a href="#account" class="nav-link active" id="account-tab" data-toggle="pill" role="tab" aria-controls="account" aria-selected="true">
						<i class="fa fa-home text-center mr-1"></i>
						Account
					</a>
					<!-- <a href="#password" class="nav-link" id="account-tab" data-toggle="pill" role="tab" aria-controls="account" aria-selected="false">
						<i class="fa fa-key text-center mr-1"></i>
						Password
					</a>
					<a href="#security" class="nav-link" id="account-tab" data-toggle="pill" role="tab" aria-controls="account" aria-selected="false">
						<i class="fa fa-user text-center mr-1"></i>
						Security
					</a>
					<a href="#application" class="nav-link" id="account-tab" data-toggle="pill" role="tab" aria-controls="account" aria-selected="false">
						<i class="fa fa-tv text-center mr-1"></i>
						Application
					</a>
					<a href="#notification" class="nav-link" id="account-tab" data-toggle="pill" role="tab" aria-controls="account" aria-selected="false">
						<i class="fa fa-bell text-center mr-1"></i>
						Notification
					</a>
					<a href="#singout" class="nav-link" id="account-tab" data-toggle="pill" role="tab" aria-controls="account" aria-selected="false">
						<i class="fa fa-sign-out text-center mr-1"></i>	
						Sing out
					</a> -->
				</div>
			</div>
			<div class="tab-content p-4 p-md-5" id="v-pills-tabContent">
				<div class="tab-pane fade show active" id="account" role="tabpanel" aria-labelledby="account-tab">
					{% if messages %}
						{% for message in messages %}
					        <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
					            <div id="form_errors">
					                    <strong>{{ message }}</strong>   
					            </div>
					            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					                <span aria-hidden="true">&times;</span>
					            </button>
					        </div>
				        {% endfor %}
				    {% endif %}
					<h3 class="mb-4">Account Settings</h3>
					<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label>Full Name</label>
								<input name="name" type="text" class="form-control" value="{{ user.name }}" placeholder="Your Name">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>Username</label>
								<input required name="username" type="text" class="form-control username-validation" value="{{ user.username }}">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>Phone Number</label>
								<input name="phone" type="text" class="form-control" value="{{ user.phone }}" placeholder="+12 345 678 9876">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>Email</label>
								<input disabled type="text" class="form-control" value="{{ user.email }}">
							</div>
						</div>
						<!-- <div class="col-md-6">
							<div class="form-group">
								<label>Company</label>
								<input type="text" class="form-control" value="">
							</div>
						</div> -->
						<!-- <div class="col-md-6">
							<div class="form-group">
								<label>Designation</label>
								<input type="text" class="form-control" value="">
							</div>
						</div> -->
						<div class="col-md-12">
							<div class="form-group">
								<label>Bio</label>
								<textarea  name="bio" class="form-control" rows="4" placeholder="Something About Yourself">{{ user.bio }}</textarea>
							</div>
						</div>
						<div class="col-md-6">
						    <div class="form-group">
						        <label>Upload Photo</label>
						        <!-- <div class="input-group"> -->
						            <div class="custom-file">
						                <input name="image" type="file" class="custom-file-input" id="customFile" onchange="updateFileName()">
						                <label class="custom-file-label" for="customFile" id="fileNameLabel">Choose file</label>
						            </div>
						            <!-- <div class="input-group-append ml-2">
						                <button class="btn btn-danger" type="button">Remove Photo</button>
						            </div> -->
						        <!-- </div> -->
						    </div>
						</div>
					</div> 
					<div>
						<button type="submit" class="btn btn-primary">Update</button>
						<button class="btn btn-light">Cancel</button>
					</div>
					</form>
				</div>
				<div class="tab-pane fade" id="password" role="tabpanel" aria-labelledby="password-tab">
					<h3 class="mb-4">Password Settings</h3>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label>Old password</label>
								<input type="password" class="form-control">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label>New password</label>
								<input type="password" class="form-control">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>Confirm password</label>
								<input type="password" class="form-control">
							</div>
						</div>
					</div>
					<div>
						<button class="btn btn-primary">Update</button>
						<button class="btn btn-light">Cancel</button>
					</div>
				</div>
				<div class="tab-pane fade" id="security" role="tabpanel" aria-labelledby="security-tab">
					<h3 class="mb-4">Security Settings</h3>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label>Login</label>
								<input type="text" class="form-control">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>Two-factor auth</label>
								<input type="text" class="form-control">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="recovery">
									<label class="form-check-label" for="recovery">Recovery</label>
								</div>
							</div>
						</div>
					</div>
					<div>
						<button class="btn btn-primary">Update</button>
						<button class="btn btn-light">Cancel</button>
					</div>
				</div>
				<div class="tab-pane fade" id="application" role="tabpanel" aria-labelledby="application-tab">
					<h3 class="mb-4">Application Settings</h3>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="">
									<label class="form-check-label" for="">Lorem ipsum dolor sit amet.</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="">
									<label class="form-check-label" for="">Lorem, ipsum, dolor sit amet consectetur adipisicing.</label>
								</div>
							</div>
						</div>
					</div>
					<div>
						<button class="btn btn-primary">Update</button>
						<button class="btn btn-light">Cancel</button>
					</div>
				</div>
				<div class="tab-pane fade" id="notification" role="tabpanel" aria-labelledby="notification-tab">
					<h3 class="mb-4">Notification Settings</h3>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="">
									<label class="form-check-label" for="">Lorem ipsum dolor sit amet.</label>
								</div>
							</div>
							<div class="form-group">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="">
									<label class="form-check-label" for="">Lorem, ipsum, dolor sit amet consectetur adipisicing.</label>
								</div>
							</div>
							<div class="form-group">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" id="">
									<label class="form-check-label" for="">Lorem, ipsum, dolor sit amet consectetur adipisicing.</label>
								</div>
							</div>
						</div>
					</div>
					<div>
						<button class="btn btn-primary">Update</button>
						<button class="btn btn-light">Cancel</button>
					</div>
				</div>
				<div class="tab-pane fade" id="singout" role="tabpanel" aria-labelledby="singout-tab">
					<h3 class="mb-4">Sing Out</h3>
					<div class="row">
						
					</div>
					<div>
						<button class="btn btn-primary">Sing Out</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Account Section End -->

{% endblock content %}

templates/userauths/sing-in.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Sing In{% endblock title %}

{% block content %}

<div class="auth_wrapper">
    <header class="auth_header">Sing in</header>
    <form method="POST" class="auth_form">
      {% csrf_token %}
      <div class="field email">
        <div class="input-area">
          <input type="text" required name="email" placeholder="Email Address">
          <i class="icon fas fa-envelope"></i>
          {% if messages %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if messages %}
          {% for message in messages %}
            <div class="error error-txt">
              <strong>{{ message }}</strong>
            </div>
          {% endfor %}
        {% endif %}
      </div>
      <div class="field password">
        <div class="input-area">
          <input type="password" required name="password" placeholder="Password">
          <i class="icon fas fa-lock"></i>
          <!-- <i class="error error-icon fas fa-exclamation-circle"></i> -->
        </div>
        <!-- <div class="error error-txt">Password can't be blank</div> -->
      </div>
      <div class="pass-txt"><a href="#">Forgot password?</a></div>
      <input type="submit" value="Sing in">
    </form>
  <div class="sign-txt">Not yet member? <a href="{% url 'userauths:sing-up' %}">Sign up now</a></div>
</div>

{% endblock content %}

templates/userauths/sing-up.html
{% extends 'partials/base.html' %}
{% load static %}

{% block title %}Sing Up{% endblock title %}

{% block content %}

<div class="auth_wrapper">
    <header class="auth_header">Sing up</header>
    <form method="POST" class="auth_form">
      {% csrf_token %}
      <div class="field">
        <div class="input-area">
          {{ form.email }}
          <i class="icon fas fa-envelope"></i>
          {% if form.email.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.email.errors %}
        <div class="error error-txt">
          <strong>{{ form.email.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <div class="field">
        <div class="input-area">
          {{ form.username }}
          <i class="icon fas fa-user"></i>
          {% if form.username.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.username.errors %}
        <div class="error error-txt">
          <strong>{{ form.username.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <div class="field">
        <div class="input-area">
          {{ form.password1 }}
          <i class="icon fas fa-lock"></i>
          {% if form.password1.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.password1.errors %}
        <div class="error error-txt">
          <strong>{{ form.password1.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <div class="field">
        <div class="input-area">
          {{ form.password2 }}
          <i class="icon fas fa-lock"></i>
          {% if form.password2.errors %}
          <i class="error error-icon fas fa-exclamation-circle"></i>
          {% endif %}
        </div>
        {% if form.password2.errors %}
        <div class="error error-txt">
          <strong>{{ form.password2.errors }}</strong>
        </div>
        {% endif %}
      </div>
      <input type="submit" value="Sing up">
    </form>
  <div class="sign-txt">Already have an account? <a href="{% url 'userauths:sing-in' %}">Sing in now</a></div>
</div>

{% endblock content %}