blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [

	# Blogpage
	path('', views.blog_view, name='blog'),

	# Post Details
	path('post/<pid>/', views.blog_detail_view, name='blog-detail'),

	# Blog Category
	path('category/<cid>/', views.blog_category_view, name="blog-category"),

	# Blog Tags
	path('tag/<slug:tag_slug>/', views.blog_tags, name='blog-tag'),

	# Add Post Comment
	path('ajax-add-comment/<int:pid>/', views.ajax_add_comment, name='ajax-add-comment'),

]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [

	# Homepage
	path('', views.index, name='index'),
	
	# Product
	path('products/', views.products_list_view, name='products-list'),
	path('product/<pid>/', views.product_detail_view, name='products-detail'),

	# Category
	path('category/', views.category_list_view, name='category-list'),
	path('category/<cid>/', views.category_product_list_view, name='category-product-list'),

	# Vendor
	path('vendors/', views.vendor_list_view, name='vendor-list'),
	path('vendor/<vid>/', views.vendor_detail_view, name='vendor-detail'),

	# Tags
	path('products/tag/<slug:tag_slug>/', views.tags_list, name='tags'),

	# Add Product Review
	path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax-add-review'),

	# Seacrh 
	path('search/', views.search_view, name='search'),

	# Product Filter
	path('filter-product/', views.filter_product, name='filter-product'),

	# Add To Cart 
	path('add-to-cart/', views.add_to_cart, name='add-to-cart'),

	# Cart Page
	path('cart/', views.cart_view, name='cart'),

	# Delete from cart
	path('delete-from-cart/', views.delete_from_cart, name='delete-from-cart'),

	# Update cart
	path('update-cart/', views.update_cart, name='update-cart'),

	# Wishlist page
	path('wishlist/', views.wishlist_view, name='wishlist'),

	# Add To Wishlist
	path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),

	# Remove From Wishlist
	path('remove-from-wishlist/', views.remove_from_wishlist, name='remove-from-wishlist'),

	# Contact
	path('contact/', views.contact, name='contact'),

	# Ajax Contact From
	path('ajax-contact-form/', views.ajax_contact_form, name='ajax-contact-form'),

	# About Us
	path('about/', views.about, name='about'),
    
	# Checkout Page newly added
	path('checkout/', views.checkout, name='checkout'),
    
	# Order History
    path('order-history/', views.order_history, name='order-history'),
    path('order-detail/<str:order_id>/', views.order_detail, name='order-detail'),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('userauths.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


### TEST ###

# handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewFrom(forms.ModelForm):
	review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write review', \
		'style': 'width: 100%; border: none; background: #f5f5f5; \
		padding: 5px 10px; height: 100px; border-radius: 5px 5px 0px 0px; \
		border-bottom: 2px solid #7fad39; transition: all 0.5s; margin-top: 15px; \
		margin-bottom: 15px;'}))

	class Meta:
		model = ProductReview
		fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Avg, F, ExpressionWrapper, DecimalField
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.core import serializers
from core.models import Product, Category, Vendor, CartOrder, CartOrderItems, \
ProductImages, ProductReview, Wishlist, Address, ContactUs
from core.forms import ProductReviewFrom
from taggit.models import Tag

def index(request):
	products = Product.objects.filter(product_status='published', featured=True)

	special_offers = Product.objects.filter(product_status='published').annotate(
		discount_percentage=ExpressionWrapper(
			((F('old_price') - F('price')) / F('old_price')) * 100,
			output_field=DecimalField()
		)
    ).order_by('-discount_percentage')[:9]
    
	oldest_products = Product.objects.filter(product_status='published').order_by('date')

	context = {
		"products": products,
		"special_offers": special_offers,
		"oldest_products": oldest_products,
	}
	return render(request, 'core/index.html', context)

def products_list_view(request):
	products = Product.objects.filter(product_status='published')
	context = {
		"products": products
	}
	return render(request, 'core/product-list.html', context)

def category_list_view(request):
	categories = Category.objects.all()
	context = {
		"categories": categories,
	}
	return render(request, 'core/category-list.html', context)

def category_product_list_view(request, cid):
	category = Category.objects.get(cid=cid)
	products = Product.objects.filter(product_status='published', category=category)
	context = {
		"category": category,
		"products": products,
	}
	return render(request, 'core/category-products-list.html', context)

def vendor_list_view(request):
	vendors = Vendor.objects.all()
	context = {
		'vendors': vendors,
	}
	return render(request, 'core/vendor-list.html', context)

def vendor_detail_view(request, vid):
	vendor = Vendor.objects.get(vid=vid)
	products = Product.objects.filter(product_status='published', vendor=vendor)
	context = {
		'vendor': vendor,
		'products': products,
	}
	return render(request, 'core/vendor-detail.html', context)

def product_detail_view(request, pid):
	product = Product.objects.get(pid=pid)
	# product = get_object_or_404(Product, pid=pid)
	products = Product.objects.filter(category=product.category).exclude(pid=pid)
	p_image = product.p_images.all()

	reviews = ProductReview.objects.filter(product=product).order_by('-date')
	average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
	review_form = ProductReviewFrom()

	make_review = True
	if request.user.is_authenticated:
		user_review_count = ProductReview.objects.filter(user=request.user, product=product).count() 

		if user_review_count > 0:
			make_review = False

	context = {
		'product': product,
		'p_image': p_image,
		'products': products,
		'reviews': reviews,
		'average_rating': average_rating,
		'review_form': review_form,
		'make_review': make_review,
	}
	return render(request, 'core/product-detail.html', context)

def tags_list(request, tag_slug=None):
	products = Product.objects.filter(product_status='published').order_by('-id')

	tag = None
	if tag_slug:
		tag = Tag.objects.get(slug=tag_slug)
		# tag = get_object_or_404(Tag, slug=tag_slug)
		products = products.filter(tags__in=[tag])

	context = {
		'products': products,
		'tag': tag,
	}

	return render(request, 'core/tag.html', context)

def ajax_add_review(request, pid):
	product = Product.objects.get(pk=pid)
	user = request.user
	image = user.image.url

	review = ProductReview.objects.create(
		user=user,
		product=product,
		review=request.POST['review'],
		rating=request.POST['rating'],
	)
	
	context = {
		'user': user.username,
		'review': request.POST['review'],
		'rating': request.POST['rating'],
		'image': image
	}

	average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))


	return JsonResponse(
		{
			'bool': True,
			'context': context,
			'average_reviews': average_reviews,
		}
	)

def search_view(request):
	# query = request.GET['q'] OR
	query = request.GET.get('q') 

	products = Product.objects.filter(title__icontains=query).order_by('-date')

	context = {
		'products': products,
		'query': query,
	}

	return render(request, 'core/search.html', context)

def filter_product(request):
	categories = request.GET.getlist('category[]')
	vendors = request.GET.getlist('vendor[]')

	min_price = request.GET.get('min_price')
	max_price = request.GET.get('max_price')

	products = Product.objects.filter(product_status='published').order_by('-id').distinct()

	products = products.filter(price__gte=min_price)
	products = products.filter(price__lte=max_price)

	if len(categories) > 0:
		products = products.filter(category__id__in=categories).distinct()
	if len(vendors) > 0:
		products = products.filter(vendor__id__in=vendors).distinct()

	context = {
		'products': products
	}

	data = render_to_string('core/async/product-list.html', context)
	return JsonResponse({'data': data})

def add_to_cart(request):
	cart_product = {}

	cart_product[str(request.GET['id'])] = {
		'qty': request.GET['qty'],
		'title': request.GET['title'],
		'price': request.GET['price'],
		'image': request.GET['image'],
		'pid': request.GET['pid'],
	}

	if 'cart_data_object' in request.session:
		if str(request.GET['id']) in request.session['cart_data_object']:
			cart_data = request.session['cart_data_object']
			cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
			cart_data.update(cart_data)
			request.session['cart_data_object'] = cart_data
		else:
			cart_data = request.session['cart_data_object']
			cart_data.update(cart_product)
			request.session['cart_data_object'] = cart_data
	else:
		request.session['cart_data_object'] = cart_product

	return JsonResponse({
			'data':request.session['cart_data_object'],
			'totalcartitems':len(request.session['cart_data_object'])
		})

def cart_view(request):
	cart_total_amount = 0
	if 'cart_data_object' in request.session:
		for product_id, item in request.session['cart_data_object'].items():
			cart_total_amount += int(item['qty']) * float(item['price'])

		return render(request, 'core/cart.html', {
			'cart_data': request.session['cart_data_object'],
			'totalcartitems': len(request.session['cart_data_object']),
			'cart_total_amount': cart_total_amount
		})
		
	else:
		return render(request, 'core/cart.html')

def delete_from_cart(request):
	product_id = str(request.GET['id'])
	if 'cart_data_object' in request.session:
		if product_id in request.session['cart_data_object']:
			cart_data = request.session['cart_data_object']
			del request.session['cart_data_object'][product_id]
			request.session['cart_data_object'] = cart_data

	cart_total_amount = 0
	if 'cart_data_object' in request.session:
		for product_id, item in request.session['cart_data_object'].items():
			cart_total_amount += int(item['qty']) * float(item['price'])

	context = render_to_string('core/async/cart-list.html', {
			'cart_data': request.session['cart_data_object'],
			'totalcartitems': len(request.session['cart_data_object']),
			'cart_total_amount': cart_total_amount
		})
	return JsonResponse({
			'data': context,
			'totalcartitems': len(request.session['cart_data_object']),
		})

def update_cart(request):
	product_id = str(request.GET['id'])
	product_qty = request.GET['qty']
	if 'cart_data_object' in request.session:
		if product_id in request.session['cart_data_object']:
			cart_data = request.session['cart_data_object']
			cart_data[str(request.GET['id'])]['qty'] = product_qty
			request.session['cart_data_object'] = cart_data

	cart_total_amount = 0
	if 'cart_data_object' in request.session:
		for product_id, item in request.session['cart_data_object'].items():
			cart_total_amount += int(item['qty']) * float(item['price'])


	context = render_to_string('core/async/cart-list.html', {
			'cart_data': request.session['cart_data_object'],
			'totalcartitems': len(request.session['cart_data_object']),
			'cart_total_amount': cart_total_amount
		})
	return JsonResponse({
			'data': context,
			'totalcartitems': len(request.session['cart_data_object']),
		})

@login_required
def wishlist_view(request):
	try:
		wishlist = Wishlist.objects.filter(user=request.user)
	except:
		wishlist = None

	context = {
		'wishlist': wishlist
	}
	return render(request, 'core/wishlist.html', context)

@login_required
def add_to_wishlist(request):
	product_id = request.GET['id']
	product = Product.objects.get(id=product_id)

	context = {}

	wishlist_count = Wishlist.objects.filter(product=product, user=request.user).count()

	if wishlist_count > 0:
		context	= {
			'bool': True,
			'wishlist_count': Wishlist.objects.filter(user=request.user).count()
		}
	else:
		new_wishlist = Wishlist.objects.create(
			product=product,
			user=request.user
		)
		context = {
			'bool': True,
			'wishlist_count': Wishlist.objects.filter(user=request.user).count()
		}

	return JsonResponse(context)

def remove_from_wishlist(request):
	product_id = request.GET['id']
	wishlist = Wishlist.objects.filter(user=request.user)

	product = Wishlist.objects.get(id=product_id)
	product.delete()

	context = {
		'bool': True,
		'wishlist': wishlist
	}
	qs_json = serializers.serialize('json', wishlist)
	data = render_to_string('core/async/wishlist-list.html', context)
	return JsonResponse({'data': data, 'wishlist': qs_json})

def contact(request):
	return render(request, 'core/contact.html')

def ajax_contact_form(request):
	name = request.GET['name']
	email = request.GET['email']
	message = request.GET['message']

	contact = ContactUs.objects.create(
		name=name,		
		email=email,		
		message=message,		
	)

	data = {
		'bool': True,
	}

	return JsonResponse({'data': data})

def about(request):
	return render(request, 'core/about.html')

templates/core/async/cart-list.html
<!-- Shoping Cart Section Begin -->
<section class="shoping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th class="shoping__product">{{ totalcartitems }} Product{{ totalcartitems|pluralize }}</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product_id, item in cart_data.items %}
                            <tr>
                                <td class="shoping__cart__item">
                                    <img src="{{ item.image }}" alt="">
                                    <h5>{{ item.title }}</h5>
                                </td>
                                <td class="shoping__cart__price">
                                    ${{ item.price|floatformat:2 }}
                                </td>
                                <td class="shoping__cart__quantity">
                                    <div class="quantity">
                                        <div class="pro-qty">
                                            <input type="text" value="{{ item.qty }}" class="product-qty-{{ product_id }}">
                                        </div>
                                    </div>
                                </td>
                                <td class="shoping__cart__total">
                                    ${% widthratio item.price 1 item.qty %}
                                </td>
                                <td class="shoping__cart__item__close">
                                    <button class="update-product" data-product="{{ product_id }}" style="border: none; background: none;"><i class="fa fa-retweet"></i></button>
                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                    <button class="delete-product" data-product="{{ product_id }}" style="border: none; background: none;"><i class="fa fa-trash"></i></button> 
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__btns">
                    <a href="{% url 'core:products-list' %}" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                    <!-- <a href="#" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                        Upadate Cart</a> -->
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__continue">
                    <div class="shoping__discount">
                        <h5>Discount Codes</h5>
                        <form action="#">
                            <input type="text" placeholder="Enter your coupon code">
                            <button type="submit" class="site-btn">APPLY COUPON</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__checkout">
                    <h5>Cart Total</h5>
                    <ul>
                        <li>Subtotal <span>${{ cart_total_amount|floatformat:2 }}</span></li>
                        <li>Total <span>${{ cart_total_amount|floatformat:2 }}</span></li>
                    </ul>
                    {% if totalcartitems %}
                    <a href="#" class="primary-btn">PROCEED TO CHECKOUT</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    $(document).ready(function (){
        var proQty = $('.pro-qty');
        proQty.prepend('<span class="dec qtybtn">-</span>');
        proQty.append('<span class="inc qtybtn">+</span>');
        proQty.on('click', '.qtybtn', function () {
        var $button = $(this);
        var oldValue = $button.parent().find('input').val();
        if ($button.hasClass('inc')) {
            var newVal = parseFloat(oldValue) + 1;
        } else {
            // Don't allow decrementing below zero
            if (oldValue > 0) {
                var newVal = parseFloat(oldValue) - 1;
            } else {
                newVal = 0;
            }
        }
        $button.parent().find('input').val(newVal);
        });
    })
</script>
<!-- Shoping Cart Section End -->

templates/core/async/product-list.html
{% for p in products %}
{% if p.get_percentage > 0 %}

<div class="col-lg-4 col-md-6 col-sm-6">
    <div class="main__product__item">
        <a href="{% url 'core:products-detail' p.pid %}">
            <div class="main__product__item__pic set-bg">
                <img src="{{p.image.url}}" alt="">
                <div class="main__product__percent">-{{p.get_percentage|floatformat:0}}%</div>
                <!-- <ul class="product__item__pic__hover">
                    <li><a href="#"><i class="fa fa-heart"></i></a></li>
                    <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                    <input type="hidden" value="1" class="product-quantity-{{ p.id }}" id="product-quantity">
                    <input type="hidden" value="{{ p.pid }}" class="product-pid-{{ p.id }}">
                    <input type="hidden" value="{{ p.image.url }}" class="product-image-{{ p.id }}">
                    <input type="hidden" value="{{ p.id }}" class="product-id-{{ p.id }}">
                    <input type="hidden" value="{{ p.title }}" class="product-title-{{ p.id }}">
                    <li><button data-index='{{ p.id }}' class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i></button></li>
                </ul> -->
            </div>
        </a>
        <div class="main__product__item__text">
            <span>{{p.category.title}}</span>
            <h5><a href="{% url 'core:products-detail' p.pid %}">{{p.title}}</a></h5>
            <span style="display: none" class="current-product-price-{{ p.id }}">{{p.price}}</span>
            <div class="product__item__price">${{p.price}} <span>${{p.old_price}}</span></div>
        </div>
    </div>
</div>

{% else %}

<div class="col-lg-4 col-md-6 col-sm-6">
    <div class="main__product__item">
        <a href="{% url 'core:products-detail' p.pid %}">
            <div class="main__product__item__pic set-bg">
                <img src="{{p.image.url}}" alt="">
                <!-- <ul class="product__item__pic__hover">
                    <li><a href="#"><i class="fa fa-heart"></i></a></li>
                    <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                    <input type="hidden" value="1" class="product-quantity-{{ p.id }}" id="product-quantity">
                    <input type="hidden" value="{{ p.pid }}" class="product-pid-{{ p.id }}">
                    <input type="hidden" value="{{ p.image.url }}" class="product-image-{{ p.id }}">
                    <input type="hidden" value="{{ p.id }}" class="product-id-{{ p.id }}">
                    <input type="hidden" value="{{ p.title }}" class="product-title-{{ p.id }}">
                    <li><button data-index='{{ p.id }}' class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i></button></li>
                </ul> -->
            </div>
        </a>
        <div class="main__product__item__text">
            <span>{{p.category.title}}</span>
            <h5><a href="{% url 'core:products-detail' p.pid %}">{{p.title}}</a></h5>
            <span style="display: none" class="current-product-price-{{ p.id }}">{{p.price}}</span>
            <div class="product__item__price">${{p.price}}</div>
        </div>
    </div>
</div>

{% endif %}
{% endfor %} 

templates/core/async/wishlist-list.html
<div class="cart-wrap">
	<div class="container">
        <div class="row">
		    <div class="col-md-12">
		        <div class="table-wishlist">
			        <table cellpadding="0" cellspacing="0" border="0" width="100%">
			        	<thead>
				        	<tr>
				        		<th width="45%">Product Name</th>
				        		<th width="15%">Unit Price</th>
				        		<th width="15%">Stock Status</th>
				        		<th width="15%"></th>
				        		<th width="10%"></th>
				        	</tr>
				        </thead>
				        <tbody>
				        	{% for w in wishlist %}
				        	<tr>
				        		<td width="45%">
				        			<div class="display-flex align-center">
	                                    <div class="img-product">
	                                        <img src="{{ w.product.image.url }}" alt="" class="mCS_img_loaded">
	                                    </div>
	                                    <div class="name-product">
	                                        {{w.product.title|truncatechars:25}}
	                                    </div>
                                    </div>
                                </td>
				        		<td width="15%"><span class="price">$</span><span class="price current-product-price-{{ w.product.id }}">{{w.product.price}}</span></td>
				        		<td width="15%">
				        			{% if w.product.stock_count %}
				        			<span class="in-stock-box">In Stock</span>
				        			{% else %}
				        			<span class="out-of-stock-box">Out of Stock</span>
				        			{% endif %}
				        		</td>
				        		<td width="15%">
				        			<input type="hidden" value="1" class="product-quantity-{{ w.product.id }}" id="product-quantity">
	                                <input type="hidden" value="{{ w.product.pid }}" class="product-pid-{{ w.product.id }}">
	                                <input type="hidden" value="{{ w.product.image.url }}" class="product-image-{{ w.product.id }}">
	                                <input type="hidden" value="{{ w.product.id }}" class="product-id-{{ w.product.id }}">
	                                <input type="hidden" value="{{ w.product.title }}" class="product-title-{{ w.product.id }}">
	                                {% if w.product.stock_count %}
				        			<button class="round-wishlist-btn small-btn add-to-cart-btn" data-index='{{ w.product.id }}'>Add to Cart</button>
				        			{% else %}
				        			<button class="round-wishlist-btn small-btn">Contact Us</button>
				        			{% endif %}
				        			
				        		</td>
				        		<td width="10%" class="text-center"><button style="border-style: none; background: none;" data-wishlist-product="{{ w.id }}" class="trash-icon delete-wishlist-product"><i class="fa fa-trash"></i></button></td>
				        	</tr>
				        	{% empty %}
				        	<tr>
				        		<td><p>Nothing in wishlist yet.</p></td>
				        	</tr>
				        	{% endfor %}
			        	</tbody>
			        </table>
			    </div>
		    </div>
		</div>
	</div>
</div>